// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMFirebaseStorageInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    // FindClass aborts the process outright if an exception is already pending,
    // so log and clear whatever is in flight before raising our own.
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!scoped.env || !g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// __GMFirebaseStorage_invocation_handler JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseStorage_invocation_handler(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__GMFirebaseStorage_invocation_handler((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}
// __GMFirebaseStorage_queue_buffer JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseStorage_queue_buffer(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }

    double __ret = __EXT_NATIVE__GMFirebaseStorage_queue_buffer((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}
// firebase_storage_get_instance JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_instance_D4B61195B551(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_instance((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_get_instance_with_url JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_instance_with_url_79EDBE52269B(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jstring url, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_url(env, url);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_instance_with_url((char *)__pin_url.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_url JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_url_7CA118A3D892(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_url((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_get_reference JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_reference_F53FAA806256(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_reference((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_get_reference_path JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_reference_path_E3187DCD3BCE(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_reference_path((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_get_reference_from_url JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_reference_from_url_1D89E3B95510(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_reference_from_url((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_max_download_retry_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_max_download_retry_time_9033D90A0699(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_max_download_retry_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_set_max_download_retry_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_set_max_download_retry_time_790400A33557(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_set_max_download_retry_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_max_upload_retry_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_max_upload_retry_time_599CD58010A7(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_max_upload_retry_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_set_max_upload_retry_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_set_max_upload_retry_time_8C4AFB083500(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_set_max_upload_retry_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_max_operation_retry_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_max_operation_retry_time_54831B43B0B1(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_max_operation_retry_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_set_max_operation_retry_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_set_max_operation_retry_time_52E28BD462C1(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_set_max_operation_retry_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_use_emulator JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_use_emulator_E0441016764B(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_use_emulator((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_child JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_child_CEFE6118E895(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_child((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_get_parent JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_get_parent_2A549385AEF6(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_get_parent((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_bucket JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_ref_bucket_6F60AC449AE3(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_ref_bucket((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_ref_full_path JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_ref_full_path_E5219EFF693C(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_ref_full_path((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_ref_name JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_ref_name_B519DEF325AA(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_ref_name((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_ref_is_valid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_is_valid_0CA54D3966AE(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_is_valid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_storage JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_storage_6109F7FCC46D(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_storage((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_delete JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_delete_231E0E552745(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_delete((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_get_download_url JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_get_download_url_54FF6A0BA9A5(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_get_download_url((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_get_metadata JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_get_metadata_712F54C0799E(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_get_metadata((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_update_metadata JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_update_metadata_14050D06BE4C(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_update_metadata((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_put_bytes JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_put_bytes_EC3A62493635(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_put_bytes((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_put_file JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_put_file_E75CF84590C1(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_put_file((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_get_bytes JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_get_bytes_C213E7507B00(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_get_bytes((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_get_file JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_get_file_3D7FAA51C8BF(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_get_file((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_ref_list JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_ref_list_C854ECA3D0BD(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_ref_list((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_create JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_create_A752D68874E9(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_create((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_release_A031B2EFB7F1(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_is_valid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_is_valid_4E612A4D9EF9(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_is_valid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_bucket JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_bucket_810358BBC6E4(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_bucket((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_cache_control JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_cache_control_649D8920B559(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_cache_control((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_set_cache_control JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_set_cache_control_4D0BBAE15730(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_set_cache_control((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_content_disposition JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_content_disposition_C902F02218D3(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_content_disposition((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_set_content_disposition JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_set_content_disposition_1F9A1F042EB6(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_set_content_disposition((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_content_encoding JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_content_encoding_E438647AEF62(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_content_encoding((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_set_content_encoding JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_set_content_encoding_12FC3AE12198(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_set_content_encoding((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_content_language JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_content_language_F73E3F623BFF(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_content_language((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_set_content_language JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_set_content_language_A0307EBB1AC7(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_set_content_language((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_content_type JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_content_type_64906DAA581A(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_content_type((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_set_content_type JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_set_content_type_82D74232C41E(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_set_content_type((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_creation_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_creation_time_FF85F530E628(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_creation_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_generation JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_generation_A15539FEBABB(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_generation((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_metadata_generation JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_metadata_generation_E7A4607EB341(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_metadata_generation((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_name JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_name_4FDCFDA60616(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_name((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_path JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_path_3C80F469A4CF(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_path((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_get_reference JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_get_reference_A483AC91CF6C(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_get_reference((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_size_bytes JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_size_bytes_04C78441E5C6(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_size_bytes((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_updated_time JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_updated_time_FD44081E9C74(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_updated_time((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_custom_metadata_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_custom_metadata_count_F2F4BB93C118(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_custom_metadata_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_metadata_custom_metadata_key_at JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_custom_metadata_key_at_F047686C45A8(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_custom_metadata_key_at((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_get_custom_metadata JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_get_custom_metadata_B61B08A8F657(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_get_custom_metadata((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_set_custom_metadata JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_metadata_set_custom_metadata_5E9DAFE36687(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_metadata_set_custom_metadata((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_create JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_create_FF3466AF1E41(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_create((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_release_135D22B84BE7(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_is_valid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_is_valid_A0F8781FE400(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_is_valid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_pause JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_pause_A17341745873(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_pause((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_resume JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_resume_B4451CD7164A(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_resume((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_cancel JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_cancel_16A7F9AF930B(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_cancel((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_is_paused JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_is_paused_44D5767EF42B(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_is_paused((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_bytes_transferred JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_bytes_transferred_728988D62EAC(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_bytes_transferred((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_total_byte_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_total_byte_count_B38CA782881E(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_total_byte_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_controller_get_reference JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_controller_get_reference_48546550663F(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_controller_get_reference((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_list_result_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_list_result_release_B1EBCA843296(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_list_result_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_list_result_is_valid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_list_result_is_valid_CFFCC693DC45(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_list_result_is_valid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_list_result_item_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_list_result_item_count_4055EC5F90E9(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_list_result_item_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_list_result_item_at JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_list_result_item_at_7AF67011C8EB(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_list_result_item_at((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_list_result_prefix_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_list_result_prefix_count_4B1212A77084(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_list_result_prefix_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_list_result_prefix_at JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_list_result_prefix_at_07699473217A(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_list_result_prefix_at((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_list_result_next_page_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_list_result_next_page_token_CC20FF43A9DC(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_list_result_next_page_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_metadata_md5_hash JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_storage_metadata_md5_hash_24B290EF9EC3(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_storage_metadata_md5_hash((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_storage_get_app JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_app_236CCCAAE34F(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_get_instance_for_app JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_instance_for_app_9E286571532F(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_instance_for_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_storage_get_instance_for_app_url JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_storage_get_instance_for_app_url_A652FDE19E64(JNIEnv* env, jclass /* GMFirebaseStorageBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_storage_get_instance_for_app_url((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMFirebaseStorageBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                // Log and carry on: this runs from the bridge's <clinit>, so
                // throwing here becomes ExceptionInInitializerError and takes
                // the whole app down over a lookup helper. Extension options
                // just read back empty (see ExtUtils::GetExtensionOption).
                // The usual cause is R8 shrinking the method away -- the keep
                // rules live in ExtensionCore's <YYAndroidProguard> block.
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__GMFirebaseStorage_invocation_handler", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseStorage_invocation_handler },
            { "__EXT_JNI__GMFirebaseStorage_queue_buffer", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseStorage_queue_buffer },
            { "__EXT_JNI__firebase_storage_get_instance", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_instance_D4B61195B551 },
            { "__EXT_JNI__firebase_storage_get_instance_with_url", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_instance_with_url_79EDBE52269B },
            { "__EXT_JNI__firebase_storage_url", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_url_7CA118A3D892 },
            { "__EXT_JNI__firebase_storage_get_reference", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_reference_F53FAA806256 },
            { "__EXT_JNI__firebase_storage_get_reference_path", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_reference_path_E3187DCD3BCE },
            { "__EXT_JNI__firebase_storage_get_reference_from_url", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_reference_from_url_1D89E3B95510 },
            { "__EXT_JNI__firebase_storage_max_download_retry_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_max_download_retry_time_9033D90A0699 },
            { "__EXT_JNI__firebase_storage_set_max_download_retry_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_set_max_download_retry_time_790400A33557 },
            { "__EXT_JNI__firebase_storage_max_upload_retry_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_max_upload_retry_time_599CD58010A7 },
            { "__EXT_JNI__firebase_storage_set_max_upload_retry_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_set_max_upload_retry_time_8C4AFB083500 },
            { "__EXT_JNI__firebase_storage_max_operation_retry_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_max_operation_retry_time_54831B43B0B1 },
            { "__EXT_JNI__firebase_storage_set_max_operation_retry_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_set_max_operation_retry_time_52E28BD462C1 },
            { "__EXT_JNI__firebase_storage_use_emulator", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_use_emulator_E0441016764B },
            { "__EXT_JNI__firebase_storage_ref_child", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_child_CEFE6118E895 },
            { "__EXT_JNI__firebase_storage_ref_get_parent", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_get_parent_2A549385AEF6 },
            { "__EXT_JNI__firebase_storage_ref_bucket", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_ref_bucket_6F60AC449AE3 },
            { "__EXT_JNI__firebase_storage_ref_full_path", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_ref_full_path_E5219EFF693C },
            { "__EXT_JNI__firebase_storage_ref_name", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_ref_name_B519DEF325AA },
            { "__EXT_JNI__firebase_storage_ref_is_valid", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_is_valid_0CA54D3966AE },
            { "__EXT_JNI__firebase_storage_ref_storage", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_storage_6109F7FCC46D },
            { "__EXT_JNI__firebase_storage_ref_delete", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_delete_231E0E552745 },
            { "__EXT_JNI__firebase_storage_ref_get_download_url", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_get_download_url_54FF6A0BA9A5 },
            { "__EXT_JNI__firebase_storage_ref_get_metadata", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_get_metadata_712F54C0799E },
            { "__EXT_JNI__firebase_storage_ref_update_metadata", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_update_metadata_14050D06BE4C },
            { "__EXT_JNI__firebase_storage_ref_put_bytes", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_put_bytes_EC3A62493635 },
            { "__EXT_JNI__firebase_storage_ref_put_file", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_put_file_E75CF84590C1 },
            { "__EXT_JNI__firebase_storage_ref_get_bytes", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_get_bytes_C213E7507B00 },
            { "__EXT_JNI__firebase_storage_ref_get_file", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_get_file_3D7FAA51C8BF },
            { "__EXT_JNI__firebase_storage_ref_list", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_ref_list_C854ECA3D0BD },
            { "__EXT_JNI__firebase_storage_metadata_create", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_create_A752D68874E9 },
            { "__EXT_JNI__firebase_storage_metadata_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_release_A031B2EFB7F1 },
            { "__EXT_JNI__firebase_storage_metadata_is_valid", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_is_valid_4E612A4D9EF9 },
            { "__EXT_JNI__firebase_storage_metadata_bucket", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_bucket_810358BBC6E4 },
            { "__EXT_JNI__firebase_storage_metadata_cache_control", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_cache_control_649D8920B559 },
            { "__EXT_JNI__firebase_storage_metadata_set_cache_control", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_set_cache_control_4D0BBAE15730 },
            { "__EXT_JNI__firebase_storage_metadata_content_disposition", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_content_disposition_C902F02218D3 },
            { "__EXT_JNI__firebase_storage_metadata_set_content_disposition", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_set_content_disposition_1F9A1F042EB6 },
            { "__EXT_JNI__firebase_storage_metadata_content_encoding", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_content_encoding_E438647AEF62 },
            { "__EXT_JNI__firebase_storage_metadata_set_content_encoding", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_set_content_encoding_12FC3AE12198 },
            { "__EXT_JNI__firebase_storage_metadata_content_language", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_content_language_F73E3F623BFF },
            { "__EXT_JNI__firebase_storage_metadata_set_content_language", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_set_content_language_A0307EBB1AC7 },
            { "__EXT_JNI__firebase_storage_metadata_content_type", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_content_type_64906DAA581A },
            { "__EXT_JNI__firebase_storage_metadata_set_content_type", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_set_content_type_82D74232C41E },
            { "__EXT_JNI__firebase_storage_metadata_creation_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_creation_time_FF85F530E628 },
            { "__EXT_JNI__firebase_storage_metadata_generation", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_generation_A15539FEBABB },
            { "__EXT_JNI__firebase_storage_metadata_metadata_generation", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_metadata_generation_E7A4607EB341 },
            { "__EXT_JNI__firebase_storage_metadata_name", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_name_4FDCFDA60616 },
            { "__EXT_JNI__firebase_storage_metadata_path", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_path_3C80F469A4CF },
            { "__EXT_JNI__firebase_storage_metadata_get_reference", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_get_reference_A483AC91CF6C },
            { "__EXT_JNI__firebase_storage_metadata_size_bytes", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_size_bytes_04C78441E5C6 },
            { "__EXT_JNI__firebase_storage_metadata_updated_time", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_updated_time_FD44081E9C74 },
            { "__EXT_JNI__firebase_storage_metadata_custom_metadata_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_custom_metadata_count_F2F4BB93C118 },
            { "__EXT_JNI__firebase_storage_metadata_custom_metadata_key_at", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_custom_metadata_key_at_F047686C45A8 },
            { "__EXT_JNI__firebase_storage_metadata_get_custom_metadata", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_get_custom_metadata_B61B08A8F657 },
            { "__EXT_JNI__firebase_storage_metadata_set_custom_metadata", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_metadata_set_custom_metadata_5E9DAFE36687 },
            { "__EXT_JNI__firebase_storage_controller_create", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_create_FF3466AF1E41 },
            { "__EXT_JNI__firebase_storage_controller_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_release_135D22B84BE7 },
            { "__EXT_JNI__firebase_storage_controller_is_valid", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_is_valid_A0F8781FE400 },
            { "__EXT_JNI__firebase_storage_controller_pause", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_pause_A17341745873 },
            { "__EXT_JNI__firebase_storage_controller_resume", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_resume_B4451CD7164A },
            { "__EXT_JNI__firebase_storage_controller_cancel", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_cancel_16A7F9AF930B },
            { "__EXT_JNI__firebase_storage_controller_is_paused", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_is_paused_44D5767EF42B },
            { "__EXT_JNI__firebase_storage_controller_bytes_transferred", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_bytes_transferred_728988D62EAC },
            { "__EXT_JNI__firebase_storage_controller_total_byte_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_total_byte_count_B38CA782881E },
            { "__EXT_JNI__firebase_storage_controller_get_reference", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_controller_get_reference_48546550663F },
            { "__EXT_JNI__firebase_storage_list_result_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_list_result_release_B1EBCA843296 },
            { "__EXT_JNI__firebase_storage_list_result_is_valid", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_list_result_is_valid_CFFCC693DC45 },
            { "__EXT_JNI__firebase_storage_list_result_item_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_list_result_item_count_4055EC5F90E9 },
            { "__EXT_JNI__firebase_storage_list_result_item_at", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_list_result_item_at_7AF67011C8EB },
            { "__EXT_JNI__firebase_storage_list_result_prefix_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_list_result_prefix_count_4B1212A77084 },
            { "__EXT_JNI__firebase_storage_list_result_prefix_at", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_list_result_prefix_at_07699473217A },
            { "__EXT_JNI__firebase_storage_list_result_next_page_token", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_list_result_next_page_token_CC20FF43A9DC },
            { "__EXT_JNI__firebase_storage_metadata_md5_hash", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_storage_metadata_md5_hash_24B290EF9EC3 },
            { "__EXT_JNI__firebase_storage_get_app", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_app_236CCCAAE34F },
            { "__EXT_JNI__firebase_storage_get_instance_for_app", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_instance_for_app_9E286571532F },
            { "__EXT_JNI__firebase_storage_get_instance_for_app_url", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_storage_get_instance_for_app_url_A652FDE19E64 },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
