// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMFirebaseCoreInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    // FindClass aborts the process outright if an exception is already pending,
    // so log and clear whatever is in flight before raising our own.
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!scoped.env || !g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// firebase_app_initialize JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_app_initialize_FC0B8CBB187E(JNIEnv* /* env */, jclass /* GMFirebaseCoreBridge */)
{
    double __ret = __EXT_NATIVE__firebase_app_initialize();
    return static_cast<jdouble>(__ret);
}

// firebase_app_is_initialized JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_app_is_initialized_EF8226FBB608(JNIEnv* /* env */, jclass /* GMFirebaseCoreBridge */)
{
    double __ret = __EXT_NATIVE__firebase_app_is_initialized();
    return static_cast<jdouble>(__ret);
}

// firebase_app_get_name JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_app_get_name_B910B2819AFE(JNIEnv* env, jclass /* GMFirebaseCoreBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_app_get_name();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_last_error_code JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_last_error_code_DF92CAF06828(JNIEnv* /* env */, jclass /* GMFirebaseCoreBridge */)
{
    double __ret = __EXT_NATIVE__firebase_last_error_code();
    return static_cast<jdouble>(__ret);
}

// firebase_last_error_message JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_last_error_message_190A5AC6257D(JNIEnv* env, jclass /* GMFirebaseCoreBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_last_error_message();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_app_get_default_handle JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_get_default_handle_D51F6F791929(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_get_default_handle((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_get_instance JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_get_instance_DE9C83E634C9(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jstring name, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_name(env, name);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_get_instance((char *)__pin_name.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_get_apps JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_get_apps_66B703DEAFFC(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_get_apps((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_initialize_with_options JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_initialize_with_options_EE17C8E51F3F(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_initialize_with_options((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_initialize_from_json JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_initialize_from_json_8A7867B2CA4A(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jstring json_config, jstring name, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_json_config(env, json_config);
    UtfChars __pin_name(env, name);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_initialize_from_json((char *)__pin_json_config.c_str(), (char *)__pin_name.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_handle_get_name JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_app_handle_get_name_C50D41B85B9D(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_app_handle_get_name((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_app_handle_get_options JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_handle_get_options_3528E84C2916(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_handle_get_options((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_get_default_options JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_get_default_options_F967D10EB704(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_get_default_options((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_release_handle JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_release_handle_BC8F19C0CD0E(JNIEnv* env, jclass /* GMFirebaseCoreBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_release_handle((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_set_log_level JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_set_log_level_CCADDAC66AE1(JNIEnv* /* env */, jclass /* GMFirebaseCoreBridge */, jdouble level)
{
    double __ret = __EXT_NATIVE__firebase_set_log_level(static_cast<double>(level));
    return static_cast<jdouble>(__ret);
}

// firebase_get_log_level JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_get_log_level_EC7C8A0D9A51(JNIEnv* /* env */, jclass /* GMFirebaseCoreBridge */)
{
    double __ret = __EXT_NATIVE__firebase_get_log_level();
    return static_cast<jdouble>(__ret);
}

// firebase_get_sdk_version JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_get_sdk_version_36038D875034(JNIEnv* env, jclass /* GMFirebaseCoreBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_get_sdk_version();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMFirebaseCoreBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                // Log and carry on: this runs from the bridge's <clinit>, so
                // throwing here becomes ExceptionInInitializerError and takes
                // the whole app down over a lookup helper. Extension options
                // just read back empty (see ExtUtils::GetExtensionOption).
                // The usual cause is R8 shrinking the method away -- the keep
                // rules live in ExtensionCore's <YYAndroidProguard> block.
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__firebase_app_initialize", "()D", (void*)__JNI_WRAPPER__firebase_app_initialize_FC0B8CBB187E },
            { "__EXT_JNI__firebase_app_is_initialized", "()D", (void*)__JNI_WRAPPER__firebase_app_is_initialized_EF8226FBB608 },
            { "__EXT_JNI__firebase_app_get_name", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_app_get_name_B910B2819AFE },
            { "__EXT_JNI__firebase_last_error_code", "()D", (void*)__JNI_WRAPPER__firebase_last_error_code_DF92CAF06828 },
            { "__EXT_JNI__firebase_last_error_message", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_last_error_message_190A5AC6257D },
            { "__EXT_JNI__firebase_app_get_default_handle", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_get_default_handle_D51F6F791929 },
            { "__EXT_JNI__firebase_app_get_instance", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_get_instance_DE9C83E634C9 },
            { "__EXT_JNI__firebase_app_get_apps", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_get_apps_66B703DEAFFC },
            { "__EXT_JNI__firebase_app_initialize_with_options", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_initialize_with_options_EE17C8E51F3F },
            { "__EXT_JNI__firebase_app_initialize_from_json", "(Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_initialize_from_json_8A7867B2CA4A },
            { "__EXT_JNI__firebase_app_handle_get_name", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_app_handle_get_name_C50D41B85B9D },
            { "__EXT_JNI__firebase_app_handle_get_options", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_handle_get_options_3528E84C2916 },
            { "__EXT_JNI__firebase_app_get_default_options", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_get_default_options_F967D10EB704 },
            { "__EXT_JNI__firebase_app_release_handle", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_release_handle_BC8F19C0CD0E },
            { "__EXT_JNI__firebase_set_log_level", "(D)D", (void*)__JNI_WRAPPER__firebase_set_log_level_CCADDAC66AE1 },
            { "__EXT_JNI__firebase_get_log_level", "()D", (void*)__JNI_WRAPPER__firebase_get_log_level_EC7C8A0D9A51 },
            { "__EXT_JNI__firebase_get_sdk_version", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_get_sdk_version_36038D875034 },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
