param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $ProjectPath)) {
    throw "GameMaker project not found: $ProjectPath"
}

$raw = Get-Content -Raw -LiteralPath $ProjectPath

# Product order is deterministic. It is intentionally independent from linker
# order; GMFirebaseModule.cmake computes SDK dependency/link order separately.
$map = [ordered]@{
    "GMFirebaseAnalytics"      = "analytics"
    "GMFirebaseAppCheck"       = "app_check"
    "GMFirebaseAuth"           = "auth"
    "GMFirebaseDatabase"       = "database"
    "GMFirebaseFirestore"      = "firestore"
    "GMFirebaseFunctions"      = "functions"
    "GMFirebaseInstallations"  = "installations"
    "GMFirebaseMessaging"      = "messaging"
    "GMFirebaseRemoteConfig"   = "remote_config"
    "GMFirebaseStorage"        = "storage"
    "GMFirebaseUMP"            = "ump"
}

$enabled = New-Object System.Collections.Generic.List[string]
$enabledExtensions = New-Object System.Collections.Generic.List[string]

foreach ($entry in $map.GetEnumerator()) {
    # Current GameMaker .yyp files reference extension resources by name/path.
    # Matching the exact extension resource name is robust across the different
    # resource object layouts used by recent IDE/runtime versions.
    $pattern = '(?<![A-Za-z0-9_])' + [regex]::Escape($entry.Key) + '(?![A-Za-z0-9_])'
    if ([regex]::IsMatch($raw, $pattern)) {
        [void]$enabled.Add($entry.Value)
        [void]$enabledExtensions.Add($entry.Key)
    }
}

$moduleList = $enabled -join ';'
$extensionList = $enabledExtensions -join ', '

$lines = @(
    '# AUTO-GENERATED by GMFirebaseCore/generate_firebase_modules.ps1'
    '# Source GameMaker project:'
    ('#   ' + $ProjectPath)
    ('# Enabled extensions: ' + $(if ($extensionList) { $extensionList } else { '(none)' }))
    ('set(GMFIREBASE_PROJECT_MODULES "' + $moduleList + '")')
)

$directory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $directory)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

$newContent = ($lines -join [Environment]::NewLine) + [Environment]::NewLine
$oldContent = if (Test-Path -LiteralPath $OutputPath) {
    Get-Content -Raw -LiteralPath $OutputPath
} else {
    $null
}

if ($oldContent -ne $newContent) {
    $temp = $OutputPath + '.tmp'
    [System.IO.File]::WriteAllText($temp, $newContent, [System.Text.UTF8Encoding]::new($false))
    Move-Item -Force -LiteralPath $temp -Destination $OutputPath
    Write-Host "[GMFirebaseCore] Firebase module manifest updated: $moduleList"
} else {
    Write-Host "[GMFirebaseCore] Firebase module manifest unchanged: $moduleList"
}
