// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__GMFirebaseAuth_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

GMEXPORT double __EXT_NATIVE__firebase_auth_get_auth();
GMEXPORT char* __EXT_NATIVE__firebase_auth_language_code();
GMEXPORT double __EXT_NATIVE__firebase_auth_set_language_code(char* language_code);
GMEXPORT double __EXT_NATIVE__firebase_auth_use_app_language();
GMEXPORT double __EXT_NATIVE__firebase_auth_use_emulator(char* host, double port);
GMEXPORT double __EXT_NATIVE__firebase_auth_current_user(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_out();
GMEXPORT double __EXT_NATIVE__firebase_auth_fetch_providers_for_email(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_with_custom_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_with_credential(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_and_retrieve_data_with_credential(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_anonymously(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_with_email_and_password(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_create_user_with_email_and_password(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_send_password_reset_email(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_add_state_listener(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_remove_state_listener(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_add_id_token_listener(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_remove_id_token_listener(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_credential_provider(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_credential_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_credential_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_email_auth_provider_get_credential(char* email, char* password, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_facebook_auth_provider_get_credential(char* access_token, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_game_center_auth_provider_get_credential(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_game_center_auth_provider_is_player_authenticated();
GMEXPORT double __EXT_NATIVE__firebase_auth_github_auth_provider_get_credential(char* token, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_google_auth_provider_get_credential(char* id_token, char* access_token, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_oauth_provider_get_credential(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_oauth_provider_get_credential_with_nonce(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_play_games_auth_provider_get_credential(char* server_auth_code, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_twitter_auth_provider_get_credential(char* token, char* secret, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_phone_verify_phone_number(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_phone_get_credential(char* verification_id, char* verification_code, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_phone_credential_sms_code(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_phone_resending_token_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_phone_listener_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_get_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_user_uid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_user_email(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_user_display_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_user_photo_url(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_user_provider_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_user_phone_number(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_is_email_verified(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_is_anonymous(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_creation_timestamp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_last_sign_in_timestamp(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_get_token(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_update_password(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_update_profile(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_send_email_verification(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_send_email_verification_before_updating_email(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_reauthenticate(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_reauthenticate_and_retrieve_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_link_with_credential(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_unlink(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_reload(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_delete(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_federated_oauth_provider_create(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_federated_oauth_provider_set_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_federated_oauth_provider_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_with_provider(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_with_custom_token_result(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_and_retrieve_data_with_credential_result(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_anonymously_result(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_sign_in_with_email_and_password_result(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_create_user_with_email_and_password_result(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_provider_data_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_provider_data_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_reauthenticate_with_provider(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_link_with_provider(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_reauthenticate_and_retrieve_data_result(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_link_with_credential_result(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_user_update_phone_number_credential(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_get_app(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_get_current_instance_handle(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_get_instance_for_app(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_use_instance(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_auth_instance_get_app(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_auth_email_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_facebook_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_game_center_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_github_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_google_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_microsoft_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_play_games_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_twitter_auth_provider_id();
GMEXPORT char* __EXT_NATIVE__firebase_auth_yahoo_auth_provider_id();
GMEXPORT double __EXT_NATIVE__firebase_auth_game_center_auth_provider_get_credential_last_result(char* __arg_buffer, double __arg_buffer_length);

