// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMFirebaseAnalyticsInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    // FindClass aborts the process outright if an exception is already pending,
    // so log and clear whatever is in flight before raising our own.
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!scoped.env || !g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// __GMFirebaseAnalytics_invocation_handler JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseAnalytics_invocation_handler(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__GMFirebaseAnalytics_invocation_handler((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}
// __GMFirebaseAnalytics_queue_buffer JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseAnalytics_queue_buffer(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }

    double __ret = __EXT_NATIVE__GMFirebaseAnalytics_queue_buffer((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}
// firebase_analytics_initialize JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_analytics_initialize_E34927795131(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */)
{
    double __ret = __EXT_NATIVE__firebase_analytics_initialize();
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_terminate JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_analytics_terminate_6ACE03CFA924(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */)
{
    double __ret = __EXT_NATIVE__firebase_analytics_terminate();
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_analytics_collection_enabled JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_analytics_collection_enabled_17FC5444D5B4(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */, jdouble enabled)
{
    double __ret = __EXT_NATIVE__firebase_analytics_set_analytics_collection_enabled(static_cast<double>(enabled));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_consent JNI wrapper signature: (DDDD)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_consent_40B844F37DDF(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */, jdouble ad_storage, jdouble analytics_storage, jdouble ad_user_data, jdouble ad_personalization)
{
    double __ret = __EXT_NATIVE__firebase_analytics_set_consent(static_cast<double>(ad_storage), static_cast<double>(analytics_storage), static_cast<double>(ad_user_data), static_cast<double>(ad_personalization));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_log_event JNI wrapper signature: (Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_analytics_log_event_E65BB54C7224(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jstring name)
{
    UtfChars __pin_name(env, name);
    double __ret = __EXT_NATIVE__firebase_analytics_log_event((char *)__pin_name.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_log_event_string JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_analytics_log_event_string_8D964F96B7EB(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jstring name, jstring parameter_name, jstring parameter_value)
{
    UtfChars __pin_name(env, name);
    UtfChars __pin_parameter_name(env, parameter_name);
    UtfChars __pin_parameter_value(env, parameter_value);
    double __ret = __EXT_NATIVE__firebase_analytics_log_event_string((char *)__pin_name.c_str(), (char *)__pin_parameter_name.c_str(), (char *)__pin_parameter_value.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_log_event_number JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_log_event_number_CD66711ABE84(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jstring name, jstring parameter_name, jdouble parameter_value)
{
    UtfChars __pin_name(env, name);
    UtfChars __pin_parameter_name(env, parameter_name);
    double __ret = __EXT_NATIVE__firebase_analytics_log_event_number((char *)__pin_name.c_str(), (char *)__pin_parameter_name.c_str(), static_cast<double>(parameter_value));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_log_event_params JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_log_event_params_1025C48B430D(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_log_event_params((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_default_event_parameters JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_default_event_parameters_B11E75DD8692(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_set_default_event_parameters((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_log_apple_transaction JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_log_apple_transaction_0FFC6D026386(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_log_apple_transaction((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_user_property JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_user_property_22B7BABAF04F(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jstring name, jstring value)
{
    UtfChars __pin_name(env, name);
    UtfChars __pin_value(env, value);
    double __ret = __EXT_NATIVE__firebase_analytics_set_user_property((char *)__pin_name.c_str(), (char *)__pin_value.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_user_id JNI wrapper signature: (Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_user_id_656BC15C41C9(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jstring user_id)
{
    UtfChars __pin_user_id(env, user_id);
    double __ret = __EXT_NATIVE__firebase_analytics_set_user_id((char *)__pin_user_id.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_session_timeout_duration JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_session_timeout_duration_A3C1354A8B00(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */, jdouble milliseconds)
{
    double __ret = __EXT_NATIVE__firebase_analytics_set_session_timeout_duration(static_cast<double>(milliseconds));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_reset_analytics_data JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_analytics_reset_analytics_data_DEB605C9CAD2(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */)
{
    double __ret = __EXT_NATIVE__firebase_analytics_reset_analytics_data();
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_get_analytics_instance_id JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_get_analytics_instance_id_AA1EC9E83398(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_get_analytics_instance_id((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_get_session_id JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_get_session_id_A4AB942D602C(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_get_session_id((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_notify_app_lifecycle_termination JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_analytics_notify_app_lifecycle_termination_200D35A3AFA8(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */)
{
    double __ret = __EXT_NATIVE__firebase_analytics_notify_app_lifecycle_termination();
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_is_desktop_initialized JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_analytics_is_desktop_initialized_F1A09438951E(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */)
{
    double __ret = __EXT_NATIVE__firebase_analytics_is_desktop_initialized();
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_desktop_debug_mode JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_desktop_debug_mode_2E60848C3F37(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */, jdouble enabled)
{
    double __ret = __EXT_NATIVE__firebase_analytics_set_desktop_debug_mode(static_cast<double>(enabled));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_set_log_callback JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_set_log_callback_FA7FADCA7032(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_set_log_callback((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_initiate_on_device_conversion_measurement_email JNI wrapper signature: (Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_email_8EAE13436821(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jstring email_address)
{
    UtfChars __pin_email_address(env, email_address);
    double __ret = __EXT_NATIVE__firebase_analytics_initiate_on_device_conversion_measurement_email((char *)__pin_email_address.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_initiate_on_device_conversion_measurement_phone JNI wrapper signature: (Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_phone_AC4C7D6D0634(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jstring phone_number)
{
    UtfChars __pin_phone_number(env, phone_number);
    double __ret = __EXT_NATIVE__firebase_analytics_initiate_on_device_conversion_measurement_phone((char *)__pin_phone_number.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_notify_app_lifecycle_change JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_analytics_notify_app_lifecycle_change_3C025E179BCF(JNIEnv* /* env */, jclass /* GMFirebaseAnalyticsBridge */, jdouble state)
{
    double __ret = __EXT_NATIVE__firebase_analytics_notify_app_lifecycle_change(static_cast<double>(state));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_initiate_on_device_conversion_measurement_hashed_email JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_hashed_email_56601A82470D(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_initiate_on_device_conversion_measurement_hashed_email((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_initiate_on_device_conversion_measurement_hashed_phone JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_hashed_phone_123B0E9FC2D4(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_initiate_on_device_conversion_measurement_hashed_phone((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_analytics_initialize_for_app JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_analytics_initialize_for_app_E679125A1C08(JNIEnv* env, jclass /* GMFirebaseAnalyticsBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_analytics_initialize_for_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMFirebaseAnalyticsBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                // Log and carry on: this runs from the bridge's <clinit>, so
                // throwing here becomes ExceptionInInitializerError and takes
                // the whole app down over a lookup helper. Extension options
                // just read back empty (see ExtUtils::GetExtensionOption).
                // The usual cause is R8 shrinking the method away -- the keep
                // rules live in ExtensionCore's <YYAndroidProguard> block.
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__GMFirebaseAnalytics_invocation_handler", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseAnalytics_invocation_handler },
            { "__EXT_JNI__GMFirebaseAnalytics_queue_buffer", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseAnalytics_queue_buffer },
            { "__EXT_JNI__firebase_analytics_initialize", "()D", (void*)__JNI_WRAPPER__firebase_analytics_initialize_E34927795131 },
            { "__EXT_JNI__firebase_analytics_terminate", "()D", (void*)__JNI_WRAPPER__firebase_analytics_terminate_6ACE03CFA924 },
            { "__EXT_JNI__firebase_analytics_set_analytics_collection_enabled", "(D)D", (void*)__JNI_WRAPPER__firebase_analytics_set_analytics_collection_enabled_17FC5444D5B4 },
            { "__EXT_JNI__firebase_analytics_set_consent", "(DDDD)D", (void*)__JNI_WRAPPER__firebase_analytics_set_consent_40B844F37DDF },
            { "__EXT_JNI__firebase_analytics_log_event", "(Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_analytics_log_event_E65BB54C7224 },
            { "__EXT_JNI__firebase_analytics_log_event_string", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_analytics_log_event_string_8D964F96B7EB },
            { "__EXT_JNI__firebase_analytics_log_event_number", "(Ljava/lang/String;Ljava/lang/String;D)D", (void*)__JNI_WRAPPER__firebase_analytics_log_event_number_CD66711ABE84 },
            { "__EXT_JNI__firebase_analytics_log_event_params", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_log_event_params_1025C48B430D },
            { "__EXT_JNI__firebase_analytics_set_default_event_parameters", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_set_default_event_parameters_B11E75DD8692 },
            { "__EXT_JNI__firebase_analytics_log_apple_transaction", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_log_apple_transaction_0FFC6D026386 },
            { "__EXT_JNI__firebase_analytics_set_user_property", "(Ljava/lang/String;Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_analytics_set_user_property_22B7BABAF04F },
            { "__EXT_JNI__firebase_analytics_set_user_id", "(Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_analytics_set_user_id_656BC15C41C9 },
            { "__EXT_JNI__firebase_analytics_set_session_timeout_duration", "(D)D", (void*)__JNI_WRAPPER__firebase_analytics_set_session_timeout_duration_A3C1354A8B00 },
            { "__EXT_JNI__firebase_analytics_reset_analytics_data", "()D", (void*)__JNI_WRAPPER__firebase_analytics_reset_analytics_data_DEB605C9CAD2 },
            { "__EXT_JNI__firebase_analytics_get_analytics_instance_id", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_get_analytics_instance_id_AA1EC9E83398 },
            { "__EXT_JNI__firebase_analytics_get_session_id", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_get_session_id_A4AB942D602C },
            { "__EXT_JNI__firebase_analytics_notify_app_lifecycle_termination", "()D", (void*)__JNI_WRAPPER__firebase_analytics_notify_app_lifecycle_termination_200D35A3AFA8 },
            { "__EXT_JNI__firebase_analytics_is_desktop_initialized", "()D", (void*)__JNI_WRAPPER__firebase_analytics_is_desktop_initialized_F1A09438951E },
            { "__EXT_JNI__firebase_analytics_set_desktop_debug_mode", "(D)D", (void*)__JNI_WRAPPER__firebase_analytics_set_desktop_debug_mode_2E60848C3F37 },
            { "__EXT_JNI__firebase_analytics_set_log_callback", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_set_log_callback_FA7FADCA7032 },
            { "__EXT_JNI__firebase_analytics_initiate_on_device_conversion_measurement_email", "(Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_email_8EAE13436821 },
            { "__EXT_JNI__firebase_analytics_initiate_on_device_conversion_measurement_phone", "(Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_phone_AC4C7D6D0634 },
            { "__EXT_JNI__firebase_analytics_notify_app_lifecycle_change", "(D)D", (void*)__JNI_WRAPPER__firebase_analytics_notify_app_lifecycle_change_3C025E179BCF },
            { "__EXT_JNI__firebase_analytics_initiate_on_device_conversion_measurement_hashed_email", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_hashed_email_56601A82470D },
            { "__EXT_JNI__firebase_analytics_initiate_on_device_conversion_measurement_hashed_phone", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_initiate_on_device_conversion_measurement_hashed_phone_123B0E9FC2D4 },
            { "__EXT_JNI__firebase_analytics_initialize_for_app", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_analytics_initialize_for_app_E679125A1C08 },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
