// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMFirebaseAppCheckInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    // FindClass aborts the process outright if an exception is already pending,
    // so log and clear whatever is in flight before raising our own.
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!scoped.env || !g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// __GMFirebaseAppCheck_invocation_handler JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseAppCheck_invocation_handler(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__GMFirebaseAppCheck_invocation_handler((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}
// firebase_app_check_set_provider_factory JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_app_check_set_provider_factory_7BBDC859B2A1(JNIEnv* /* env */, jclass /* GMFirebaseAppCheckBridge */, jdouble provider)
{
    double __ret = __EXT_NATIVE__firebase_app_check_set_provider_factory(static_cast<double>(provider));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_debug_provider_set_debug_token JNI wrapper signature: (Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_app_check_debug_provider_set_debug_token_E21A3EABCCA7(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jstring token)
{
    UtfChars __pin_token(env, token);
    double __ret = __EXT_NATIVE__firebase_app_check_debug_provider_set_debug_token((char *)__pin_token.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_set_token_auto_refresh_enabled JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_app_check_set_token_auto_refresh_enabled_0A2BECD6BB67(JNIEnv* /* env */, jclass /* GMFirebaseAppCheckBridge */, jdouble enabled)
{
    double __ret = __EXT_NATIVE__firebase_app_check_set_token_auto_refresh_enabled(static_cast<double>(enabled));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_get_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_get_token_1444DEB81766(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_get_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_get_limited_use_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_get_limited_use_token_E61CC96B15A2(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_get_limited_use_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_add_listener JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_add_listener_686EBB06E834(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_add_listener((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_remove_listener JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_remove_listener_AE6FF45417E3(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_remove_listener((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_get_app JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_get_app_7D4E4BB7A3B8(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_get_app((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_get_instance_handle JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_get_instance_handle_EC9D9C3437AC(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_get_instance_handle((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_get_instance_for_app JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_get_instance_for_app_61ED37D926C6(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_get_instance_for_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_instance_get_app JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_instance_get_app_9342B67476BB(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_instance_get_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_instance_set_token_auto_refresh_enabled JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_instance_set_token_auto_refresh_enabled_4C4F03F63026(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_instance_set_token_auto_refresh_enabled((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_instance_get_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_instance_get_token_1D174591A0B2(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_instance_get_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_instance_get_limited_use_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_instance_get_limited_use_token_1D108E674710(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_instance_get_limited_use_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_app_check_instance_add_listener JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_app_check_instance_add_listener_0B82D99B96F0(JNIEnv* env, jclass /* GMFirebaseAppCheckBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_app_check_instance_add_listener((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMFirebaseAppCheckBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                // Log and carry on: this runs from the bridge's <clinit>, so
                // throwing here becomes ExceptionInInitializerError and takes
                // the whole app down over a lookup helper. Extension options
                // just read back empty (see ExtUtils::GetExtensionOption).
                // The usual cause is R8 shrinking the method away -- the keep
                // rules live in ExtensionCore's <YYAndroidProguard> block.
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__GMFirebaseAppCheck_invocation_handler", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseAppCheck_invocation_handler },
            { "__EXT_JNI__firebase_app_check_set_provider_factory", "(D)D", (void*)__JNI_WRAPPER__firebase_app_check_set_provider_factory_7BBDC859B2A1 },
            { "__EXT_JNI__firebase_app_check_debug_provider_set_debug_token", "(Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_app_check_debug_provider_set_debug_token_E21A3EABCCA7 },
            { "__EXT_JNI__firebase_app_check_set_token_auto_refresh_enabled", "(D)D", (void*)__JNI_WRAPPER__firebase_app_check_set_token_auto_refresh_enabled_0A2BECD6BB67 },
            { "__EXT_JNI__firebase_app_check_get_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_get_token_1444DEB81766 },
            { "__EXT_JNI__firebase_app_check_get_limited_use_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_get_limited_use_token_E61CC96B15A2 },
            { "__EXT_JNI__firebase_app_check_add_listener", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_add_listener_686EBB06E834 },
            { "__EXT_JNI__firebase_app_check_remove_listener", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_remove_listener_AE6FF45417E3 },
            { "__EXT_JNI__firebase_app_check_get_app", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_get_app_7D4E4BB7A3B8 },
            { "__EXT_JNI__firebase_app_check_get_instance_handle", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_get_instance_handle_EC9D9C3437AC },
            { "__EXT_JNI__firebase_app_check_get_instance_for_app", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_get_instance_for_app_61ED37D926C6 },
            { "__EXT_JNI__firebase_app_check_instance_get_app", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_instance_get_app_9342B67476BB },
            { "__EXT_JNI__firebase_app_check_instance_set_token_auto_refresh_enabled", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_instance_set_token_auto_refresh_enabled_4C4F03F63026 },
            { "__EXT_JNI__firebase_app_check_instance_get_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_instance_get_token_1D174591A0B2 },
            { "__EXT_JNI__firebase_app_check_instance_get_limited_use_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_instance_get_limited_use_token_1D108E674710 },
            { "__EXT_JNI__firebase_app_check_instance_add_listener", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_app_check_instance_add_listener_0B82D99B96F0 },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
