// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMFirebaseMessagingInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    // FindClass aborts the process outright if an exception is already pending,
    // so log and clear whatever is in flight before raising our own.
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!scoped.env || !g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// __GMFirebaseMessaging_invocation_handler JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseMessaging_invocation_handler(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__GMFirebaseMessaging_invocation_handler((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}
// __GMFirebaseMessaging_queue_buffer JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseMessaging_queue_buffer(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }

    double __ret = __EXT_NATIVE__GMFirebaseMessaging_queue_buffer((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}
// firebase_messaging_initialize JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_initialize_736AD75959D0(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_initialize();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_terminate JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_terminate_A4EFB58D3377(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_terminate();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_set_token_registration_on_init_enabled JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_messaging_set_token_registration_on_init_enabled_5F0836B360E1(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */, jdouble enabled)
{
    double __ret = __EXT_NATIVE__firebase_messaging_set_token_registration_on_init_enabled(static_cast<double>(enabled));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_is_token_registration_on_init_enabled JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_is_token_registration_on_init_enabled_BE68D2B9EBA0(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_is_token_registration_on_init_enabled();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_delivery_metrics_export_to_big_query_enabled JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_delivery_metrics_export_to_big_query_enabled_497E4A6029DB(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_delivery_metrics_export_to_big_query_enabled();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_set_delivery_metrics_export_to_big_query JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_messaging_set_delivery_metrics_export_to_big_query_8336AABA3767(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */, jdouble enabled)
{
    double __ret = __EXT_NATIVE__firebase_messaging_set_delivery_metrics_export_to_big_query(static_cast<double>(enabled));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_request_permission JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_request_permission_901C6B89A6DC(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_request_permission((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_get_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_get_token_55EA7FCB6DB3(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_get_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_delete_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_delete_token_12D594F0BA74(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_delete_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_subscribe JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_subscribe_3DB4BA9C321A(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_subscribe((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_unsubscribe JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_unsubscribe_5E9DFE1A987E(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_unsubscribe((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_poll_message JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_poll_message_087D97D27BC3(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_poll_message();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_poll_token JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_poll_token_A683A48E0727(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_poll_token();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_current_token JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_current_token_E1DC4B4DA756(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_current_token();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_from JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_from_94B3AA4685E4(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_from();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_to JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_to_100A53AB2F72(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_to();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_collapse_key JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_collapse_key_B11C41434F4B(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_collapse_key();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_message_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_message_id_E4C71BCC21BA(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_message_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_message_type JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_message_type_36A00B2379E4(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_message_type();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_priority JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_priority_B6A766A43119(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_priority();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_original_priority JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_original_priority_C90A38C84010(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_original_priority();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_time_to_live JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_time_to_live_59E03215BC3B(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_time_to_live();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_sent_time JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_sent_time_F866354CE5E1(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_sent_time();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_error JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_error_7B906280E375(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_error();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_error_description JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_error_description_F3979A7BB928(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_error_description();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_link JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_link_5487140A571B(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_link();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_opened JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_notification_opened_58C6D98E04C1(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_notification_opened();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_data_count JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_data_count_3915E494C3EA(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_data_count();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_data_key_at JNI wrapper signature: (D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_data_key_at_31627E2223C5(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jdouble index)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_data_key_at(static_cast<double>(index));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_get_data JNI wrapper signature: (Ljava/lang/String;)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_get_data_6245CB3908E3(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jstring key)
{
    UtfChars __pin_key(env, key);
    const char* __out = __EXT_NATIVE__firebase_messaging_message_get_data((char *)__pin_key.c_str());
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_raw_data_size JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_raw_data_size_3EFFBA866E45(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_raw_data_size();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_raw_data_copy JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_message_raw_data_copy_A9C63C2CA883(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_message_raw_data_copy((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_has_notification JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_has_notification_2D5664684C29(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_has_notification();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_notification_title JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_title_57C6ADD3C238(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_title();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_body JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_body_9461D4037E4D(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_body();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_icon JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_icon_05B403FF66FB(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_icon();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_sound JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_sound_7E2288032D89(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_sound();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_badge JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_badge_C52957405004(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_badge();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_tag JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_tag_367771A7EBDE(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_tag();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_color JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_color_F3CA37C151E0(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_color();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_click_action JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_click_action_8733D0EA2605(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_click_action();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_body_loc_key JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_body_loc_key_67598F45D27E(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_body_loc_key();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_body_loc_args_count JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_notification_body_loc_args_count_9B73ED554332(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_notification_body_loc_args_count();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_notification_body_loc_args_at JNI wrapper signature: (D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_body_loc_args_at_DB54D1D9B38E(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jdouble index)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_body_loc_args_at(static_cast<double>(index));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_title_loc_key JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_title_loc_key_F5AF415312B5(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_title_loc_key();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_title_loc_args_count JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_messaging_message_notification_title_loc_args_count_012C5EE19E8C(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */)
{
    double __ret = __EXT_NATIVE__firebase_messaging_message_notification_title_loc_args_count();
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_message_notification_title_loc_args_at JNI wrapper signature: (D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_title_loc_args_at_131ED499CF5A(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jdouble index)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_title_loc_args_at(static_cast<double>(index));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_message_notification_android_channel_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_messaging_message_notification_android_channel_id_7F7DFEF3AAF6(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_messaging_message_notification_android_channel_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_messaging_initialize_with_options JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__firebase_messaging_initialize_with_options_E0A9DBEE7B01(JNIEnv* /* env */, jclass /* GMFirebaseMessagingBridge */, jdouble suppress_notification_permission_prompt)
{
    double __ret = __EXT_NATIVE__firebase_messaging_initialize_with_options(static_cast<double>(suppress_notification_permission_prompt));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_initialize_for_app JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_initialize_for_app_0F73246042D0(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_initialize_for_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_messaging_initialize_for_app_with_options JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_messaging_initialize_for_app_with_options_CC9EB9647639(JNIEnv* env, jclass /* GMFirebaseMessagingBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_messaging_initialize_for_app_with_options((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMFirebaseMessagingBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                // Log and carry on: this runs from the bridge's <clinit>, so
                // throwing here becomes ExceptionInInitializerError and takes
                // the whole app down over a lookup helper. Extension options
                // just read back empty (see ExtUtils::GetExtensionOption).
                // The usual cause is R8 shrinking the method away -- the keep
                // rules live in ExtensionCore's <YYAndroidProguard> block.
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__GMFirebaseMessaging_invocation_handler", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseMessaging_invocation_handler },
            { "__EXT_JNI__GMFirebaseMessaging_queue_buffer", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseMessaging_queue_buffer },
            { "__EXT_JNI__firebase_messaging_initialize", "()D", (void*)__JNI_WRAPPER__firebase_messaging_initialize_736AD75959D0 },
            { "__EXT_JNI__firebase_messaging_terminate", "()D", (void*)__JNI_WRAPPER__firebase_messaging_terminate_A4EFB58D3377 },
            { "__EXT_JNI__firebase_messaging_set_token_registration_on_init_enabled", "(D)D", (void*)__JNI_WRAPPER__firebase_messaging_set_token_registration_on_init_enabled_5F0836B360E1 },
            { "__EXT_JNI__firebase_messaging_is_token_registration_on_init_enabled", "()D", (void*)__JNI_WRAPPER__firebase_messaging_is_token_registration_on_init_enabled_BE68D2B9EBA0 },
            { "__EXT_JNI__firebase_messaging_delivery_metrics_export_to_big_query_enabled", "()D", (void*)__JNI_WRAPPER__firebase_messaging_delivery_metrics_export_to_big_query_enabled_497E4A6029DB },
            { "__EXT_JNI__firebase_messaging_set_delivery_metrics_export_to_big_query", "(D)D", (void*)__JNI_WRAPPER__firebase_messaging_set_delivery_metrics_export_to_big_query_8336AABA3767 },
            { "__EXT_JNI__firebase_messaging_request_permission", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_request_permission_901C6B89A6DC },
            { "__EXT_JNI__firebase_messaging_get_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_get_token_55EA7FCB6DB3 },
            { "__EXT_JNI__firebase_messaging_delete_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_delete_token_12D594F0BA74 },
            { "__EXT_JNI__firebase_messaging_subscribe", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_subscribe_3DB4BA9C321A },
            { "__EXT_JNI__firebase_messaging_unsubscribe", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_unsubscribe_5E9DFE1A987E },
            { "__EXT_JNI__firebase_messaging_poll_message", "()D", (void*)__JNI_WRAPPER__firebase_messaging_poll_message_087D97D27BC3 },
            { "__EXT_JNI__firebase_messaging_poll_token", "()D", (void*)__JNI_WRAPPER__firebase_messaging_poll_token_A683A48E0727 },
            { "__EXT_JNI__firebase_messaging_current_token", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_current_token_E1DC4B4DA756 },
            { "__EXT_JNI__firebase_messaging_message_from", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_from_94B3AA4685E4 },
            { "__EXT_JNI__firebase_messaging_message_to", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_to_100A53AB2F72 },
            { "__EXT_JNI__firebase_messaging_message_collapse_key", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_collapse_key_B11C41434F4B },
            { "__EXT_JNI__firebase_messaging_message_message_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_message_id_E4C71BCC21BA },
            { "__EXT_JNI__firebase_messaging_message_message_type", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_message_type_36A00B2379E4 },
            { "__EXT_JNI__firebase_messaging_message_priority", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_priority_B6A766A43119 },
            { "__EXT_JNI__firebase_messaging_message_original_priority", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_original_priority_C90A38C84010 },
            { "__EXT_JNI__firebase_messaging_message_time_to_live", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_time_to_live_59E03215BC3B },
            { "__EXT_JNI__firebase_messaging_message_sent_time", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_sent_time_F866354CE5E1 },
            { "__EXT_JNI__firebase_messaging_message_error", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_error_7B906280E375 },
            { "__EXT_JNI__firebase_messaging_message_error_description", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_error_description_F3979A7BB928 },
            { "__EXT_JNI__firebase_messaging_message_link", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_link_5487140A571B },
            { "__EXT_JNI__firebase_messaging_message_notification_opened", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_opened_58C6D98E04C1 },
            { "__EXT_JNI__firebase_messaging_message_data_count", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_data_count_3915E494C3EA },
            { "__EXT_JNI__firebase_messaging_message_data_key_at", "(D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_data_key_at_31627E2223C5 },
            { "__EXT_JNI__firebase_messaging_message_get_data", "(Ljava/lang/String;)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_get_data_6245CB3908E3 },
            { "__EXT_JNI__firebase_messaging_message_raw_data_size", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_raw_data_size_3EFFBA866E45 },
            { "__EXT_JNI__firebase_messaging_message_raw_data_copy", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_message_raw_data_copy_A9C63C2CA883 },
            { "__EXT_JNI__firebase_messaging_message_has_notification", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_has_notification_2D5664684C29 },
            { "__EXT_JNI__firebase_messaging_message_notification_title", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_title_57C6ADD3C238 },
            { "__EXT_JNI__firebase_messaging_message_notification_body", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_body_9461D4037E4D },
            { "__EXT_JNI__firebase_messaging_message_notification_icon", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_icon_05B403FF66FB },
            { "__EXT_JNI__firebase_messaging_message_notification_sound", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_sound_7E2288032D89 },
            { "__EXT_JNI__firebase_messaging_message_notification_badge", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_badge_C52957405004 },
            { "__EXT_JNI__firebase_messaging_message_notification_tag", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_tag_367771A7EBDE },
            { "__EXT_JNI__firebase_messaging_message_notification_color", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_color_F3CA37C151E0 },
            { "__EXT_JNI__firebase_messaging_message_notification_click_action", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_click_action_8733D0EA2605 },
            { "__EXT_JNI__firebase_messaging_message_notification_body_loc_key", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_body_loc_key_67598F45D27E },
            { "__EXT_JNI__firebase_messaging_message_notification_body_loc_args_count", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_body_loc_args_count_9B73ED554332 },
            { "__EXT_JNI__firebase_messaging_message_notification_body_loc_args_at", "(D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_body_loc_args_at_DB54D1D9B38E },
            { "__EXT_JNI__firebase_messaging_message_notification_title_loc_key", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_title_loc_key_F5AF415312B5 },
            { "__EXT_JNI__firebase_messaging_message_notification_title_loc_args_count", "()D", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_title_loc_args_count_012C5EE19E8C },
            { "__EXT_JNI__firebase_messaging_message_notification_title_loc_args_at", "(D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_title_loc_args_at_131ED499CF5A },
            { "__EXT_JNI__firebase_messaging_message_notification_android_channel_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_messaging_message_notification_android_channel_id_7F7DFEF3AAF6 },
            { "__EXT_JNI__firebase_messaging_initialize_with_options", "(D)D", (void*)__JNI_WRAPPER__firebase_messaging_initialize_with_options_E0A9DBEE7B01 },
            { "__EXT_JNI__firebase_messaging_initialize_for_app", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_initialize_for_app_0F73246042D0 },
            { "__EXT_JNI__firebase_messaging_initialize_for_app_with_options", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_messaging_initialize_for_app_with_options_CC9EB9647639 },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
