// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMFirebaseAuthInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    // FindClass aborts the process outright if an exception is already pending,
    // so log and clear whatever is in flight before raising our own.
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!scoped.env || !g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// __GMFirebaseAuth_invocation_handler JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMFirebaseAuth_invocation_handler(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__GMFirebaseAuth_invocation_handler((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}
// firebase_auth_get_auth JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_auth_get_auth_8182A8988FC6(JNIEnv* /* env */, jclass /* GMFirebaseAuthBridge */)
{
    double __ret = __EXT_NATIVE__firebase_auth_get_auth();
    return static_cast<jdouble>(__ret);
}

// firebase_auth_language_code JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_language_code_14C2CD532B29(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_language_code();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_set_language_code JNI wrapper signature: (Ljava/lang/String;)D
static jdouble __JNI_WRAPPER__firebase_auth_set_language_code_4D2AEDE70536(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring language_code)
{
    UtfChars __pin_language_code(env, language_code);
    double __ret = __EXT_NATIVE__firebase_auth_set_language_code((char *)__pin_language_code.c_str());
    return static_cast<jdouble>(__ret);
}

// firebase_auth_use_app_language JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_auth_use_app_language_331AAA8857F2(JNIEnv* /* env */, jclass /* GMFirebaseAuthBridge */)
{
    double __ret = __EXT_NATIVE__firebase_auth_use_app_language();
    return static_cast<jdouble>(__ret);
}

// firebase_auth_use_emulator JNI wrapper signature: (Ljava/lang/String;D)D
static jdouble __JNI_WRAPPER__firebase_auth_use_emulator_252B285789C7(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring host, jdouble port)
{
    UtfChars __pin_host(env, host);
    double __ret = __EXT_NATIVE__firebase_auth_use_emulator((char *)__pin_host.c_str(), static_cast<double>(port));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_current_user JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_current_user_7B796B3887DC(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_current_user((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_out JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_auth_sign_out_F5E40F27DD06(JNIEnv* /* env */, jclass /* GMFirebaseAuthBridge */)
{
    double __ret = __EXT_NATIVE__firebase_auth_sign_out();
    return static_cast<jdouble>(__ret);
}

// firebase_auth_fetch_providers_for_email JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_fetch_providers_for_email_1F4ED31C1680(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_fetch_providers_for_email((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_with_custom_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_with_custom_token_AC142E0F09D2(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_with_custom_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_with_credential JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_with_credential_7213EC016E6B(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_with_credential((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_and_retrieve_data_with_credential JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_and_retrieve_data_with_credential_5FAB6247162B(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_and_retrieve_data_with_credential((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_anonymously JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_anonymously_5F2B6520C27D(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_anonymously((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_with_email_and_password JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_with_email_and_password_70B1E9AB8379(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_with_email_and_password((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_create_user_with_email_and_password JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_create_user_with_email_and_password_4C124CA61074(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_create_user_with_email_and_password((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_send_password_reset_email JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_send_password_reset_email_944C25B02D40(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_send_password_reset_email((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_add_state_listener JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_add_state_listener_7D14C19C37C9(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_add_state_listener((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_remove_state_listener JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_remove_state_listener_6340879501B7(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_remove_state_listener((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_add_id_token_listener JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_add_id_token_listener_6190655110DF(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_add_id_token_listener((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_remove_id_token_listener JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_remove_id_token_listener_A15A9616FE6F(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_remove_id_token_listener((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_credential_provider JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_credential_provider_FD85CD228573(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_credential_provider((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_credential_is_valid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_credential_is_valid_60DDFC047C03(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_credential_is_valid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_credential_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_credential_release_11E254EB232D(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_credential_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_email_auth_provider_get_credential JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_email_auth_provider_get_credential_CDBC3277C8D8(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring email, jstring password, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_email(env, email);
    UtfChars __pin_password(env, password);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_email_auth_provider_get_credential((char *)__pin_email.c_str(), (char *)__pin_password.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_facebook_auth_provider_get_credential JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_facebook_auth_provider_get_credential_AE2FF785466B(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring access_token, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_access_token(env, access_token);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_facebook_auth_provider_get_credential((char *)__pin_access_token.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_game_center_auth_provider_get_credential JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_game_center_auth_provider_get_credential_B53F602C5817(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_game_center_auth_provider_get_credential((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_game_center_auth_provider_is_player_authenticated JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__firebase_auth_game_center_auth_provider_is_player_authenticated_AE7DD74FCA2B(JNIEnv* /* env */, jclass /* GMFirebaseAuthBridge */)
{
    double __ret = __EXT_NATIVE__firebase_auth_game_center_auth_provider_is_player_authenticated();
    return static_cast<jdouble>(__ret);
}

// firebase_auth_github_auth_provider_get_credential JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_github_auth_provider_get_credential_109D046DCDBB(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring token, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_token(env, token);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_github_auth_provider_get_credential((char *)__pin_token.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_google_auth_provider_get_credential JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_google_auth_provider_get_credential_C8740BDEDDFC(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring id_token, jstring access_token, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_id_token(env, id_token);
    UtfChars __pin_access_token(env, access_token);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_google_auth_provider_get_credential((char *)__pin_id_token.c_str(), (char *)__pin_access_token.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_oauth_provider_get_credential JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_oauth_provider_get_credential_2F55B80D97F6(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_oauth_provider_get_credential((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_oauth_provider_get_credential_with_nonce JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_oauth_provider_get_credential_with_nonce_6C0AC3F44269(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_oauth_provider_get_credential_with_nonce((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_play_games_auth_provider_get_credential JNI wrapper signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_play_games_auth_provider_get_credential_C562F1B99653(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring server_auth_code, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_server_auth_code(env, server_auth_code);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_play_games_auth_provider_get_credential((char *)__pin_server_auth_code.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_twitter_auth_provider_get_credential JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_twitter_auth_provider_get_credential_8C3FADDC2B14(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring token, jstring secret, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_token(env, token);
    UtfChars __pin_secret(env, secret);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_twitter_auth_provider_get_credential((char *)__pin_token.c_str(), (char *)__pin_secret.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_phone_verify_phone_number JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_phone_verify_phone_number_6234F3569C9E(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_phone_verify_phone_number((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_phone_get_credential JNI wrapper signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_phone_get_credential_EDBEF13765EB(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jstring verification_id, jstring verification_code, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    UtfChars __pin_verification_id(env, verification_id);
    UtfChars __pin_verification_code(env, verification_code);
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_phone_get_credential((char *)__pin_verification_id.c_str(), (char *)__pin_verification_code.c_str(), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_phone_credential_sms_code JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_phone_credential_sms_code_EAEC19889CB4(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_phone_credential_sms_code((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_phone_resending_token_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_phone_resending_token_release_BBA9313A7AD7(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_phone_resending_token_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_phone_listener_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_phone_listener_release_3B38AE474DA8(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_phone_listener_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_get_info JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_get_info_00E3F250CE08(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_get_info((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_release_2641D3568439(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_is_valid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_is_valid_A379114D92DD(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_is_valid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_uid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_user_uid_0D4DF9E5C83C(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_user_uid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_user_email JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_user_email_2853F0CCC676(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_user_email((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_user_display_name JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_user_display_name_E3211D45C20E(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_user_display_name((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_user_photo_url JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_user_photo_url_BBB5A78CECBE(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_user_photo_url((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_user_provider_id JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_user_provider_id_CA961B2C0B1B(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_user_provider_id((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_user_phone_number JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_user_phone_number_00E2D1A08E65(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__firebase_auth_user_phone_number((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_user_is_email_verified JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_is_email_verified_BE12DA2A99AA(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_is_email_verified((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_is_anonymous JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_is_anonymous_AC45A964DAA0(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_is_anonymous((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_creation_timestamp JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_creation_timestamp_A939E413DE57(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_creation_timestamp((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_last_sign_in_timestamp JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_last_sign_in_timestamp_8CA535661918(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_last_sign_in_timestamp((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_get_token JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_get_token_19C43586C996(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_get_token((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_update_password JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_update_password_2E5CB54C946F(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_update_password((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_update_profile JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_update_profile_C93B748EBA2E(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_update_profile((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_send_email_verification JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_send_email_verification_DAF52215E524(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_send_email_verification((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_send_email_verification_before_updating_email JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_send_email_verification_before_updating_email_4EA2DB356B53(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_send_email_verification_before_updating_email((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_reauthenticate JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_reauthenticate_935CAB1306B5(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_reauthenticate((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_reauthenticate_and_retrieve_data JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_reauthenticate_and_retrieve_data_2EFCC1F1F55C(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_reauthenticate_and_retrieve_data((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_link_with_credential JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_link_with_credential_3FDD85A29A0F(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_link_with_credential((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_unlink JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_unlink_D733545CC0E4(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_unlink((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_reload JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_reload_C74A3B321B84(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_reload((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_delete JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_delete_865FB55F0884(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_delete((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_federated_oauth_provider_create JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_federated_oauth_provider_create_26B31F3D6018(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_federated_oauth_provider_create((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_federated_oauth_provider_set_data JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_federated_oauth_provider_set_data_0839531734C5(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_federated_oauth_provider_set_data((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_federated_oauth_provider_release JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_federated_oauth_provider_release_502A5E97302F(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_federated_oauth_provider_release((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_with_provider JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_with_provider_F2EDC2F610A8(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_with_provider((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_with_custom_token_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_with_custom_token_result_7D11AA603906(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_with_custom_token_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_and_retrieve_data_with_credential_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_and_retrieve_data_with_credential_result_78BB6457DB20(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_and_retrieve_data_with_credential_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_anonymously_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_anonymously_result_1FC69F986A83(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_anonymously_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_sign_in_with_email_and_password_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_sign_in_with_email_and_password_result_2495FA885D60(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_sign_in_with_email_and_password_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_create_user_with_email_and_password_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_create_user_with_email_and_password_result_CA038FEAFF9B(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_create_user_with_email_and_password_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_provider_data_count JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_provider_data_count_522CFA3CC4B9(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_provider_data_count((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_provider_data_at JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_provider_data_at_4BA24292134A(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_provider_data_at((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_reauthenticate_with_provider JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_reauthenticate_with_provider_A12185BB2061(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_reauthenticate_with_provider((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_link_with_provider JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_link_with_provider_1600D1235B3E(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_link_with_provider((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_reauthenticate_and_retrieve_data_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_reauthenticate_and_retrieve_data_result_AE971A84F6D8(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_reauthenticate_and_retrieve_data_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_link_with_credential_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_link_with_credential_result_94130CA9F9F9(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_link_with_credential_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_user_update_phone_number_credential JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_user_update_phone_number_credential_B461DF1EEC40(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_user_update_phone_number_credential((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_get_app JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_get_app_0AA5B87F73D8(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_get_app((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_get_current_instance_handle JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_get_current_instance_handle_6803C999E76B(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_get_current_instance_handle((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_get_instance_for_app JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_get_instance_for_app_7373E41CC0E4(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_get_instance_for_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_use_instance JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_use_instance_1019A6265546(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_use_instance((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_instance_get_app JNI wrapper signature: (Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_instance_get_app_FF26F44B5196(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_instance_get_app((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// firebase_auth_email_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_email_auth_provider_id_C53F81E50B98(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_email_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_facebook_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_facebook_auth_provider_id_D153A91243CA(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_facebook_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_game_center_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_game_center_auth_provider_id_4C47BD58C190(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_game_center_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_github_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_github_auth_provider_id_83FE8B78E7D9(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_github_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_google_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_google_auth_provider_id_452B89ACF968(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_google_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_microsoft_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_microsoft_auth_provider_id_C09A0A036490(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_microsoft_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_play_games_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_play_games_auth_provider_id_649A77B11D3F(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_play_games_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_twitter_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_twitter_auth_provider_id_0A072293DEC4(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_twitter_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_yahoo_auth_provider_id JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__firebase_auth_yahoo_auth_provider_id_80664E2E07B3(JNIEnv* env, jclass /* GMFirebaseAuthBridge */)
{
    const char* __out = __EXT_NATIVE__firebase_auth_yahoo_auth_provider_id();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// firebase_auth_game_center_auth_provider_get_credential_last_result JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__firebase_auth_game_center_auth_provider_get_credential_last_result_2C2EFE07EC4E(JNIEnv* env, jclass /* GMFirebaseAuthBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__firebase_auth_game_center_auth_provider_get_credential_last_result((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMFirebaseAuthBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                // Log and carry on: this runs from the bridge's <clinit>, so
                // throwing here becomes ExceptionInInitializerError and takes
                // the whole app down over a lookup helper. Extension options
                // just read back empty (see ExtUtils::GetExtensionOption).
                // The usual cause is R8 shrinking the method away -- the keep
                // rules live in ExtensionCore's <YYAndroidProguard> block.
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__GMFirebaseAuth_invocation_handler", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMFirebaseAuth_invocation_handler },
            { "__EXT_JNI__firebase_auth_get_auth", "()D", (void*)__JNI_WRAPPER__firebase_auth_get_auth_8182A8988FC6 },
            { "__EXT_JNI__firebase_auth_language_code", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_language_code_14C2CD532B29 },
            { "__EXT_JNI__firebase_auth_set_language_code", "(Ljava/lang/String;)D", (void*)__JNI_WRAPPER__firebase_auth_set_language_code_4D2AEDE70536 },
            { "__EXT_JNI__firebase_auth_use_app_language", "()D", (void*)__JNI_WRAPPER__firebase_auth_use_app_language_331AAA8857F2 },
            { "__EXT_JNI__firebase_auth_use_emulator", "(Ljava/lang/String;D)D", (void*)__JNI_WRAPPER__firebase_auth_use_emulator_252B285789C7 },
            { "__EXT_JNI__firebase_auth_current_user", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_current_user_7B796B3887DC },
            { "__EXT_JNI__firebase_auth_sign_out", "()D", (void*)__JNI_WRAPPER__firebase_auth_sign_out_F5E40F27DD06 },
            { "__EXT_JNI__firebase_auth_fetch_providers_for_email", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_fetch_providers_for_email_1F4ED31C1680 },
            { "__EXT_JNI__firebase_auth_sign_in_with_custom_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_with_custom_token_AC142E0F09D2 },
            { "__EXT_JNI__firebase_auth_sign_in_with_credential", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_with_credential_7213EC016E6B },
            { "__EXT_JNI__firebase_auth_sign_in_and_retrieve_data_with_credential", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_and_retrieve_data_with_credential_5FAB6247162B },
            { "__EXT_JNI__firebase_auth_sign_in_anonymously", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_anonymously_5F2B6520C27D },
            { "__EXT_JNI__firebase_auth_sign_in_with_email_and_password", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_with_email_and_password_70B1E9AB8379 },
            { "__EXT_JNI__firebase_auth_create_user_with_email_and_password", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_create_user_with_email_and_password_4C124CA61074 },
            { "__EXT_JNI__firebase_auth_send_password_reset_email", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_send_password_reset_email_944C25B02D40 },
            { "__EXT_JNI__firebase_auth_add_state_listener", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_add_state_listener_7D14C19C37C9 },
            { "__EXT_JNI__firebase_auth_remove_state_listener", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_remove_state_listener_6340879501B7 },
            { "__EXT_JNI__firebase_auth_add_id_token_listener", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_add_id_token_listener_6190655110DF },
            { "__EXT_JNI__firebase_auth_remove_id_token_listener", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_remove_id_token_listener_A15A9616FE6F },
            { "__EXT_JNI__firebase_auth_credential_provider", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_credential_provider_FD85CD228573 },
            { "__EXT_JNI__firebase_auth_credential_is_valid", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_credential_is_valid_60DDFC047C03 },
            { "__EXT_JNI__firebase_auth_credential_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_credential_release_11E254EB232D },
            { "__EXT_JNI__firebase_auth_email_auth_provider_get_credential", "(Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_email_auth_provider_get_credential_CDBC3277C8D8 },
            { "__EXT_JNI__firebase_auth_facebook_auth_provider_get_credential", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_facebook_auth_provider_get_credential_AE2FF785466B },
            { "__EXT_JNI__firebase_auth_game_center_auth_provider_get_credential", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_game_center_auth_provider_get_credential_B53F602C5817 },
            { "__EXT_JNI__firebase_auth_game_center_auth_provider_is_player_authenticated", "()D", (void*)__JNI_WRAPPER__firebase_auth_game_center_auth_provider_is_player_authenticated_AE7DD74FCA2B },
            { "__EXT_JNI__firebase_auth_github_auth_provider_get_credential", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_github_auth_provider_get_credential_109D046DCDBB },
            { "__EXT_JNI__firebase_auth_google_auth_provider_get_credential", "(Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_google_auth_provider_get_credential_C8740BDEDDFC },
            { "__EXT_JNI__firebase_auth_oauth_provider_get_credential", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_oauth_provider_get_credential_2F55B80D97F6 },
            { "__EXT_JNI__firebase_auth_oauth_provider_get_credential_with_nonce", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_oauth_provider_get_credential_with_nonce_6C0AC3F44269 },
            { "__EXT_JNI__firebase_auth_play_games_auth_provider_get_credential", "(Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_play_games_auth_provider_get_credential_C562F1B99653 },
            { "__EXT_JNI__firebase_auth_twitter_auth_provider_get_credential", "(Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_twitter_auth_provider_get_credential_8C3FADDC2B14 },
            { "__EXT_JNI__firebase_auth_phone_verify_phone_number", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_phone_verify_phone_number_6234F3569C9E },
            { "__EXT_JNI__firebase_auth_phone_get_credential", "(Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_phone_get_credential_EDBEF13765EB },
            { "__EXT_JNI__firebase_auth_phone_credential_sms_code", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_phone_credential_sms_code_EAEC19889CB4 },
            { "__EXT_JNI__firebase_auth_phone_resending_token_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_phone_resending_token_release_BBA9313A7AD7 },
            { "__EXT_JNI__firebase_auth_phone_listener_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_phone_listener_release_3B38AE474DA8 },
            { "__EXT_JNI__firebase_auth_user_get_info", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_get_info_00E3F250CE08 },
            { "__EXT_JNI__firebase_auth_user_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_release_2641D3568439 },
            { "__EXT_JNI__firebase_auth_user_is_valid", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_is_valid_A379114D92DD },
            { "__EXT_JNI__firebase_auth_user_uid", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_user_uid_0D4DF9E5C83C },
            { "__EXT_JNI__firebase_auth_user_email", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_user_email_2853F0CCC676 },
            { "__EXT_JNI__firebase_auth_user_display_name", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_user_display_name_E3211D45C20E },
            { "__EXT_JNI__firebase_auth_user_photo_url", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_user_photo_url_BBB5A78CECBE },
            { "__EXT_JNI__firebase_auth_user_provider_id", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_user_provider_id_CA961B2C0B1B },
            { "__EXT_JNI__firebase_auth_user_phone_number", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_user_phone_number_00E2D1A08E65 },
            { "__EXT_JNI__firebase_auth_user_is_email_verified", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_is_email_verified_BE12DA2A99AA },
            { "__EXT_JNI__firebase_auth_user_is_anonymous", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_is_anonymous_AC45A964DAA0 },
            { "__EXT_JNI__firebase_auth_user_creation_timestamp", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_creation_timestamp_A939E413DE57 },
            { "__EXT_JNI__firebase_auth_user_last_sign_in_timestamp", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_last_sign_in_timestamp_8CA535661918 },
            { "__EXT_JNI__firebase_auth_user_get_token", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_get_token_19C43586C996 },
            { "__EXT_JNI__firebase_auth_user_update_password", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_update_password_2E5CB54C946F },
            { "__EXT_JNI__firebase_auth_user_update_profile", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_update_profile_C93B748EBA2E },
            { "__EXT_JNI__firebase_auth_user_send_email_verification", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_send_email_verification_DAF52215E524 },
            { "__EXT_JNI__firebase_auth_user_send_email_verification_before_updating_email", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_send_email_verification_before_updating_email_4EA2DB356B53 },
            { "__EXT_JNI__firebase_auth_user_reauthenticate", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_reauthenticate_935CAB1306B5 },
            { "__EXT_JNI__firebase_auth_user_reauthenticate_and_retrieve_data", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_reauthenticate_and_retrieve_data_2EFCC1F1F55C },
            { "__EXT_JNI__firebase_auth_user_link_with_credential", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_link_with_credential_3FDD85A29A0F },
            { "__EXT_JNI__firebase_auth_user_unlink", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_unlink_D733545CC0E4 },
            { "__EXT_JNI__firebase_auth_user_reload", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_reload_C74A3B321B84 },
            { "__EXT_JNI__firebase_auth_user_delete", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_delete_865FB55F0884 },
            { "__EXT_JNI__firebase_auth_federated_oauth_provider_create", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_federated_oauth_provider_create_26B31F3D6018 },
            { "__EXT_JNI__firebase_auth_federated_oauth_provider_set_data", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_federated_oauth_provider_set_data_0839531734C5 },
            { "__EXT_JNI__firebase_auth_federated_oauth_provider_release", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_federated_oauth_provider_release_502A5E97302F },
            { "__EXT_JNI__firebase_auth_sign_in_with_provider", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_with_provider_F2EDC2F610A8 },
            { "__EXT_JNI__firebase_auth_sign_in_with_custom_token_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_with_custom_token_result_7D11AA603906 },
            { "__EXT_JNI__firebase_auth_sign_in_and_retrieve_data_with_credential_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_and_retrieve_data_with_credential_result_78BB6457DB20 },
            { "__EXT_JNI__firebase_auth_sign_in_anonymously_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_anonymously_result_1FC69F986A83 },
            { "__EXT_JNI__firebase_auth_sign_in_with_email_and_password_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_sign_in_with_email_and_password_result_2495FA885D60 },
            { "__EXT_JNI__firebase_auth_create_user_with_email_and_password_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_create_user_with_email_and_password_result_CA038FEAFF9B },
            { "__EXT_JNI__firebase_auth_user_provider_data_count", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_provider_data_count_522CFA3CC4B9 },
            { "__EXT_JNI__firebase_auth_user_provider_data_at", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_provider_data_at_4BA24292134A },
            { "__EXT_JNI__firebase_auth_user_reauthenticate_with_provider", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_reauthenticate_with_provider_A12185BB2061 },
            { "__EXT_JNI__firebase_auth_user_link_with_provider", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_link_with_provider_1600D1235B3E },
            { "__EXT_JNI__firebase_auth_user_reauthenticate_and_retrieve_data_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_reauthenticate_and_retrieve_data_result_AE971A84F6D8 },
            { "__EXT_JNI__firebase_auth_user_link_with_credential_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_link_with_credential_result_94130CA9F9F9 },
            { "__EXT_JNI__firebase_auth_user_update_phone_number_credential", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_user_update_phone_number_credential_B461DF1EEC40 },
            { "__EXT_JNI__firebase_auth_get_app", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_get_app_0AA5B87F73D8 },
            { "__EXT_JNI__firebase_auth_get_current_instance_handle", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_get_current_instance_handle_6803C999E76B },
            { "__EXT_JNI__firebase_auth_get_instance_for_app", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_get_instance_for_app_7373E41CC0E4 },
            { "__EXT_JNI__firebase_auth_use_instance", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_use_instance_1019A6265546 },
            { "__EXT_JNI__firebase_auth_instance_get_app", "(Ljava/nio/ByteBuffer;DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_instance_get_app_FF26F44B5196 },
            { "__EXT_JNI__firebase_auth_email_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_email_auth_provider_id_C53F81E50B98 },
            { "__EXT_JNI__firebase_auth_facebook_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_facebook_auth_provider_id_D153A91243CA },
            { "__EXT_JNI__firebase_auth_game_center_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_game_center_auth_provider_id_4C47BD58C190 },
            { "__EXT_JNI__firebase_auth_github_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_github_auth_provider_id_83FE8B78E7D9 },
            { "__EXT_JNI__firebase_auth_google_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_google_auth_provider_id_452B89ACF968 },
            { "__EXT_JNI__firebase_auth_microsoft_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_microsoft_auth_provider_id_C09A0A036490 },
            { "__EXT_JNI__firebase_auth_play_games_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_play_games_auth_provider_id_649A77B11D3F },
            { "__EXT_JNI__firebase_auth_twitter_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_twitter_auth_provider_id_0A072293DEC4 },
            { "__EXT_JNI__firebase_auth_yahoo_auth_provider_id", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__firebase_auth_yahoo_auth_provider_id_80664E2E07B3 },
            { "__EXT_JNI__firebase_auth_game_center_auth_provider_get_credential_last_result", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__firebase_auth_game_center_auth_provider_get_credential_last_result_2C2EFE07EC4E },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
