#define GMFIREBASE_CORE_BUILD 1
#include "GMFirebase_core_firestore_api.h"
#include "GMFirebase_core_firestore_impl.h"

namespace
{
    // gmfb_firestore::* function signatures already match
    // GMFirebaseCoreFirestoreAPI's fields exactly, so the table can point
    // straight at them - no adapters.
    const GMFirebaseCoreFirestoreAPI kCoreFirestoreAPI = {
        GMFIREBASE_CORE_FIRESTORE_ABI_VERSION,
        static_cast<std::uint32_t>(sizeof(GMFirebaseCoreFirestoreAPI)),

        &gmfb_firestore::get_instance,
        &gmfb_firestore::get_instance_for_database,
        &gmfb_firestore::settings_get_host,
        &gmfb_firestore::settings_set_host,
        &gmfb_firestore::settings_get_ssl_enabled,
        &gmfb_firestore::settings_set_ssl_enabled,
        &gmfb_firestore::settings_get_persistence_enabled,
        &gmfb_firestore::settings_set_persistence_enabled,
        &gmfb_firestore::settings_get_cache_size_bytes,
        &gmfb_firestore::settings_set_cache_size_bytes,
        &gmfb_firestore::collection,
        &gmfb_firestore::document,
        &gmfb_firestore::collection_group,
        &gmfb_firestore::batch,
        &gmfb_firestore::set_log_level,

        &gmfb_firestore::enable_network,
        &gmfb_firestore::disable_network,
        &gmfb_firestore::terminate,
        &gmfb_firestore::clear_persistence,
        &gmfb_firestore::wait_for_pending_writes,
        &gmfb_firestore::run_transaction,

        &gmfb_firestore::collection_ref_id,
        &gmfb_firestore::collection_ref_path,
        &gmfb_firestore::collection_ref_parent,
        &gmfb_firestore::collection_ref_document,
        &gmfb_firestore::collection_ref_document_path,
        &gmfb_firestore::collection_ref_add,
        &gmfb_firestore::collection_ref_is_valid,
        &gmfb_firestore::collection_ref_release,

        &gmfb_firestore::document_ref_id,
        &gmfb_firestore::document_ref_path,
        &gmfb_firestore::document_ref_parent,
        &gmfb_firestore::document_ref_collection,
        &gmfb_firestore::document_ref_get,
        &gmfb_firestore::document_ref_set,
        &gmfb_firestore::document_ref_set_merge,
        &gmfb_firestore::document_ref_set_merge_fields,
        &gmfb_firestore::document_ref_update,
        &gmfb_firestore::document_ref_delete,
        &gmfb_firestore::document_ref_add_snapshot_listener,
        &gmfb_firestore::document_ref_is_valid,
        &gmfb_firestore::document_ref_release,

        &gmfb_firestore::query_where_equal_to,
        &gmfb_firestore::query_where_not_equal_to,
        &gmfb_firestore::query_where_less_than,
        &gmfb_firestore::query_where_less_than_or_equal_to,
        &gmfb_firestore::query_where_greater_than,
        &gmfb_firestore::query_where_greater_than_or_equal_to,
        &gmfb_firestore::query_where_array_contains,
        &gmfb_firestore::query_where_array_contains_any,
        &gmfb_firestore::query_where_in,
        &gmfb_firestore::query_where_not_in,
        &gmfb_firestore::query_order_by,
        &gmfb_firestore::query_limit,
        &gmfb_firestore::query_limit_to_last,
        &gmfb_firestore::query_start_at_snapshot,
        &gmfb_firestore::query_start_at_values,
        &gmfb_firestore::query_start_after_snapshot,
        &gmfb_firestore::query_start_after_values,
        &gmfb_firestore::query_end_before_snapshot,
        &gmfb_firestore::query_end_before_values,
        &gmfb_firestore::query_end_at_snapshot,
        &gmfb_firestore::query_end_at_values,
        &gmfb_firestore::query_get,
        &gmfb_firestore::query_add_snapshot_listener,
        &gmfb_firestore::query_is_valid,
        &gmfb_firestore::query_release,

        &gmfb_firestore::write_batch_set,
        &gmfb_firestore::write_batch_set_merge,
        &gmfb_firestore::write_batch_set_merge_fields,
        &gmfb_firestore::write_batch_update,
        &gmfb_firestore::write_batch_delete,
        &gmfb_firestore::write_batch_commit,
        &gmfb_firestore::write_batch_release,

        &gmfb_firestore::field_value_delete,
        &gmfb_firestore::field_value_server_timestamp,
        &gmfb_firestore::field_value_array_union,
        &gmfb_firestore::field_value_array_remove,
        &gmfb_firestore::field_value_increment_integer,
        &gmfb_firestore::field_value_increment_double,
        &gmfb_firestore::field_value_integer,
        &gmfb_firestore::field_value_double,
        &gmfb_firestore::field_value_timestamp,
        &gmfb_firestore::field_value_geo_point,
        &gmfb_firestore::field_value_reference,
        &gmfb_firestore::field_value_blob,
        &gmfb_firestore::field_value_null,
        &gmfb_firestore::field_value_release,

        &gmfb_firestore::document_snapshot_get_info,
        &gmfb_firestore::document_snapshot_get,
        &gmfb_firestore::document_snapshot_get_data,
        &gmfb_firestore::document_snapshot_release,

        &gmfb_firestore::query_snapshot_get_info,
        &gmfb_firestore::query_snapshot_documents,
        &gmfb_firestore::query_snapshot_document_changes,
        &gmfb_firestore::query_snapshot_release,

        &gmfb_firestore::listener_registration_remove,

        &gmfb_firestore::field_path_create,
        &gmfb_firestore::field_path_document_id,
        &gmfb_firestore::field_path_is_valid,
        &gmfb_firestore::field_path_to_string,
        &gmfb_firestore::field_path_release,

        &gmfb_firestore::filter_equal_to,
        &gmfb_firestore::filter_not_equal_to,
        &gmfb_firestore::filter_less_than,
        &gmfb_firestore::filter_less_than_or_equal_to,
        &gmfb_firestore::filter_greater_than,
        &gmfb_firestore::filter_greater_than_or_equal_to,
        &gmfb_firestore::filter_array_contains,
        &gmfb_firestore::filter_array_contains_any,
        &gmfb_firestore::filter_in,
        &gmfb_firestore::filter_not_in,
        &gmfb_firestore::filter_equal_to_field_path,
        &gmfb_firestore::filter_not_equal_to_field_path,
        &gmfb_firestore::filter_less_than_field_path,
        &gmfb_firestore::filter_less_than_or_equal_to_field_path,
        &gmfb_firestore::filter_greater_than_field_path,
        &gmfb_firestore::filter_greater_than_or_equal_to_field_path,
        &gmfb_firestore::filter_array_contains_field_path,
        &gmfb_firestore::filter_array_contains_any_field_path,
        &gmfb_firestore::filter_in_field_path,
        &gmfb_firestore::filter_not_in_field_path,
        &gmfb_firestore::filter_and,
        &gmfb_firestore::filter_or,
        &gmfb_firestore::filter_release,
        &gmfb_firestore::query_where_filter,
        &gmfb_firestore::query_where_equal_to_field_path,
        &gmfb_firestore::query_where_not_equal_to_field_path,
        &gmfb_firestore::query_where_less_than_field_path,
        &gmfb_firestore::query_where_less_than_or_equal_to_field_path,
        &gmfb_firestore::query_where_greater_than_field_path,
        &gmfb_firestore::query_where_greater_than_or_equal_to_field_path,
        &gmfb_firestore::query_where_array_contains_field_path,
        &gmfb_firestore::query_where_array_contains_any_field_path,
        &gmfb_firestore::query_where_in_field_path,
        &gmfb_firestore::query_where_not_in_field_path,
        &gmfb_firestore::query_order_by_field_path,

        &gmfb_firestore::query_count,
        &gmfb_firestore::aggregate_query_get_query,
        &gmfb_firestore::aggregate_query_is_valid,
        &gmfb_firestore::aggregate_query_get,
        &gmfb_firestore::aggregate_query_release,
        &gmfb_firestore::aggregate_snapshot_count,
        &gmfb_firestore::aggregate_snapshot_get_query,
        &gmfb_firestore::aggregate_snapshot_is_valid,
        &gmfb_firestore::aggregate_snapshot_release,

        &gmfb_firestore::add_snapshots_in_sync_listener,
        &gmfb_firestore::load_bundle,
        &gmfb_firestore::named_query,
        &gmfb_firestore::document_ref_set_merge_field_paths,
        &gmfb_firestore::write_batch_set_merge_field_paths,

        &gmfb_firestore::field_value_type,
        &gmfb_firestore::field_value_is_valid,
        &gmfb_firestore::field_value_is_null,
        &gmfb_firestore::field_value_is_boolean,
        &gmfb_firestore::field_value_is_integer,
        &gmfb_firestore::field_value_is_double,
        &gmfb_firestore::field_value_is_timestamp,
        &gmfb_firestore::field_value_is_string,
        &gmfb_firestore::field_value_is_blob,
        &gmfb_firestore::field_value_is_reference,
        &gmfb_firestore::field_value_is_geo_point,
        &gmfb_firestore::field_value_is_array,
        &gmfb_firestore::field_value_is_map,
        &gmfb_firestore::field_value_boolean_value,
        &gmfb_firestore::field_value_integer_value,
        &gmfb_firestore::field_value_double_value,
        &gmfb_firestore::field_value_string_value,
        &gmfb_firestore::field_value_blob_size,
        &gmfb_firestore::field_value_blob_copy,
        &gmfb_firestore::field_value_reference_value,
        &gmfb_firestore::field_value_timestamp_value,
        &gmfb_firestore::field_value_geo_point_value,
        &gmfb_firestore::field_value_array_value,
        &gmfb_firestore::field_value_map_value,
        &gmfb_firestore::field_value_to_string,

        &gmfb_firestore::query_get_firestore,
        &gmfb_firestore::document_ref_get_firestore,
        &gmfb_firestore::document_ref_to_string,
        &gmfb_firestore::document_ref_update_field_paths,
        &gmfb_firestore::write_batch_update_field_paths,
        &gmfb_firestore::write_batch_is_valid,
        &gmfb_firestore::settings_to_string,
        &gmfb_firestore::document_snapshot_is_valid,
        &gmfb_firestore::document_snapshot_to_string,
        &gmfb_firestore::document_snapshot_get_field_path,
        &gmfb_firestore::query_snapshot_is_valid,
        &gmfb_firestore::query_snapshot_get_query,
        &gmfb_firestore::listener_registration_is_valid,
        &gmfb_firestore::get_app,
        &gmfb_firestore::get_instance_for_app,
        &gmfb_firestore::get_instance_for_app_database,
        &gmfb_firestore::field_value_boolean,
        &gmfb_firestore::field_value_string,
        &gmfb_firestore::field_value_array,
        &gmfb_firestore::field_value_map,
        &gmfb_firestore::document_snapshot_metadata_to_string,
        &gmfb_firestore::query_snapshot_metadata_to_string,
        &gmfb_firestore::document_snapshot_exists,
        &gmfb_firestore::document_snapshot_id,
        &gmfb_firestore::document_snapshot_reference,
        &gmfb_firestore::document_snapshot_metadata_has_pending_writes,
        &gmfb_firestore::document_snapshot_metadata_is_from_cache,
        &gmfb_firestore::query_snapshot_size,
        &gmfb_firestore::query_snapshot_empty,
        &gmfb_firestore::query_snapshot_metadata_has_pending_writes,
        &gmfb_firestore::query_snapshot_metadata_is_from_cache,
    };
}

extern "C" GMFIREBASE_CORE_EXPORT
const GMFirebaseCoreFirestoreAPI* gmfirebase_core_get_firestore_api()
{
    return &kCoreFirestoreAPI;
}
