#define GMFIREBASE_CORE_BUILD 1
#include "GMFirebase_core_auth_api.h"
#include "GMFirebase_core_auth_impl.h"

namespace
{
    // gmfb_auth::* function signatures already match GMFirebaseCoreAuthAPI's
    // fields exactly, so the table can point straight at them - no adapters.
    const GMFirebaseCoreAuthAPI kCoreAuthAPI = {
        GMFIREBASE_CORE_AUTH_ABI_VERSION,
        static_cast<std::uint32_t>(sizeof(GMFirebaseCoreAuthAPI)),

        &gmfb_auth::get_auth,
        &gmfb_auth::language_code,
        &gmfb_auth::set_language_code,
        &gmfb_auth::use_app_language,
        &gmfb_auth::use_emulator,
        &gmfb_auth::current_user,
        &gmfb_auth::sign_out,
        &gmfb_auth::fetch_providers_for_email,
        &gmfb_auth::sign_in_with_custom_token,
        &gmfb_auth::sign_in_with_credential,
        &gmfb_auth::sign_in_and_retrieve_data_with_credential,
        &gmfb_auth::sign_in_anonymously,
        &gmfb_auth::sign_in_with_email_and_password,
        &gmfb_auth::create_user_with_email_and_password,
        &gmfb_auth::send_password_reset_email,
        &gmfb_auth::add_state_listener,
        &gmfb_auth::remove_state_listener,
        &gmfb_auth::add_id_token_listener,
        &gmfb_auth::remove_id_token_listener,
        &gmfb_auth::credential_provider,
        &gmfb_auth::credential_is_valid,
        &gmfb_auth::credential_release,
        &gmfb_auth::email_auth_provider_get_credential,
        &gmfb_auth::facebook_auth_provider_get_credential,
        &gmfb_auth::game_center_auth_provider_get_credential,
        &gmfb_auth::game_center_auth_provider_is_player_authenticated,
        &gmfb_auth::github_auth_provider_get_credential,
        &gmfb_auth::google_auth_provider_get_credential,
        &gmfb_auth::oauth_provider_get_credential,
        &gmfb_auth::oauth_provider_get_credential_with_nonce,
        &gmfb_auth::play_games_auth_provider_get_credential,
        &gmfb_auth::twitter_auth_provider_get_credential,
        &gmfb_auth::phone_verify_phone_number,
        &gmfb_auth::phone_get_credential,
        &gmfb_auth::phone_credential_sms_code,
        &gmfb_auth::phone_resending_token_release,
        &gmfb_auth::phone_listener_release,
        &gmfb_auth::user_get_info,
        &gmfb_auth::user_release,
        &gmfb_auth::user_is_valid,
        &gmfb_auth::user_uid,
        &gmfb_auth::user_email,
        &gmfb_auth::user_display_name,
        &gmfb_auth::user_photo_url,
        &gmfb_auth::user_provider_id,
        &gmfb_auth::user_phone_number,
        &gmfb_auth::user_is_email_verified,
        &gmfb_auth::user_is_anonymous,
        &gmfb_auth::user_creation_timestamp,
        &gmfb_auth::user_last_sign_in_timestamp,
        &gmfb_auth::user_get_token,
        &gmfb_auth::user_update_password,
        &gmfb_auth::user_update_profile,
        &gmfb_auth::user_send_email_verification,
        &gmfb_auth::user_send_email_verification_before_updating_email,
        &gmfb_auth::user_reauthenticate,
        &gmfb_auth::user_reauthenticate_and_retrieve_data,
        &gmfb_auth::user_link_with_credential,
        &gmfb_auth::user_unlink,
        &gmfb_auth::user_reload,
        &gmfb_auth::user_delete,
        &gmfb_auth::federated_oauth_provider_create,
        &gmfb_auth::federated_oauth_provider_set_data,
        &gmfb_auth::federated_oauth_provider_release,
        &gmfb_auth::sign_in_with_provider,
        &gmfb_auth::sign_in_with_custom_token_result,
        &gmfb_auth::sign_in_and_retrieve_data_with_credential_result,
        &gmfb_auth::sign_in_anonymously_result,
        &gmfb_auth::sign_in_with_email_and_password_result,
        &gmfb_auth::create_user_with_email_and_password_result,
        &gmfb_auth::user_provider_data_count,
        &gmfb_auth::user_provider_data_at,
        &gmfb_auth::user_reauthenticate_with_provider,
        &gmfb_auth::user_link_with_provider,
        &gmfb_auth::user_reauthenticate_and_retrieve_data_result,
        &gmfb_auth::user_link_with_credential_result,
        &gmfb_auth::user_update_phone_number_credential,
        &gmfb_auth::get_app,
        &gmfb_auth::get_current_instance_handle,
        &gmfb_auth::get_instance_for_app,
        &gmfb_auth::use_instance,
        &gmfb_auth::instance_get_app,
        &gmfb_auth::email_auth_provider_id,
        &gmfb_auth::facebook_auth_provider_id,
        &gmfb_auth::game_center_auth_provider_id,
        &gmfb_auth::github_auth_provider_id,
        &gmfb_auth::google_auth_provider_id,
        &gmfb_auth::microsoft_auth_provider_id,
        &gmfb_auth::play_games_auth_provider_id,
        &gmfb_auth::twitter_auth_provider_id,
        &gmfb_auth::yahoo_auth_provider_id,
        &gmfb_auth::game_center_auth_provider_get_credential_last_result,
    };
}

extern "C" GMFIREBASE_CORE_EXPORT
const GMFirebaseCoreAuthAPI* gmfirebase_core_get_auth_api()
{
    return &kCoreAuthAPI;
}
