// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__GMFirebaseDatabase_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

GMEXPORT double __EXT_NATIVE__firebase_database_get_instance(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_instance_for_url(char* url, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_database_get_url(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_reference(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_reference_at_path(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_reference_from_url(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_go_offline(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_go_online(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_purge_outstanding_writes(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_set_persistence_enabled(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_set_log_level(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_log_level(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_order_by_child(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_order_by_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_order_by_value(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_order_by_priority(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_start_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_start_at_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_end_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_end_at_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_equal_to(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_equal_to_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_limit_to_first(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_limit_to_last(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_set_keep_synchronized(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_get_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_add_value_listener(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_remove_value_listener(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_remove_all_value_listeners(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_add_child_listener(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_remove_child_listener(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_remove_all_child_listeners(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_order_by_child(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_order_by_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_order_by_value(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_order_by_priority(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_start_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_start_at_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_end_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_end_at_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_equal_to(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_equal_to_key(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_limit_to_first(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_limit_to_last(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_get_reference(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_set_keep_synchronized(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_get_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_add_value_listener(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_remove_value_listener(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_remove_all_value_listeners(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_add_child_listener(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_remove_child_listener(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_remove_all_child_listeners(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_query_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_get(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_child(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_push(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_go_online(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_go_offline(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_set_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_set_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_set_value_and_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_update_children(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_remove_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_run_transaction(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_exists(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_child(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_has_child(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_has_children(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_children_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_get_children(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_database_snapshot_key(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_get_reference(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_get_info(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_get_value(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_get_priority(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_snapshot_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_database_ref_key(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_is_root(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_get_parent(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_get_root(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_get_database(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__firebase_database_ref_get_url(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_server_timestamp(char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_ref_on_disconnect(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_on_disconnect_cancel(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_on_disconnect_remove_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_on_disconnect_set_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_on_disconnect_set_value_and_priority(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_on_disconnect_update_children(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_on_disconnect_release(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_app(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_instance_for_app(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__firebase_database_get_instance_for_app_url(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);

